### ISSUE TITLE
License

### ISSUE THREAD

**Issue by p4trykJ** [fatso83/retry-dynamic-import#7]
Hi, I would like to use this project commercially, but I am not sure if it is possible as there is no info about license. Can you provide it, please?

**Comment by fatso83** [comment]
Oooh, sorry, I have not seen this until now. I think that a project on Github is something you can use by default in whatever way you like, but I don't remember the details. 

What kind of license would you like? The only license I care about is that you attribute usage/inspiration in the consuming project's docs. Otherwise do as you like (including modifying it). If no license file is created, this _is_ the license you can follow per the current date :)

**Comment by p4trykJ** [comment]
So by default when there is no license it means that `all rights are reserved and it is not Open Source or Free`. 
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

This is the reason why it should be added in order to not violate any of your rights while using it.

**Comment by fatso83** [comment]
There are a bunch of licenses. Any one you fancy in particular? BSD, MIT? Share-alike-do-as-you-please?

**Comment by p4trykJ** [comment]
I am not. It can be MIT as you mentioned.

**Comment by fatso83** [comment]
https://github.com/fatso83/retry-dynamic-import/blob/main/LICENSE

**Comment by p4trykJ** [comment]
Thanks a lot!
